import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.https://hxhpnmdvsxejzeeyxgsw.supabase.co;
const supabaseKey = process.env.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4aHBubWR2c3hlanplZXl4Z3N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDIyNTUsImV4cCI6MjA3MjExODI1NX0.kKySqSzyEnxwkHRKT6PdUlE2_UjEjWZhTDyVO-m7O70;

export const supabase = createClient(https://hxhpnmdvsxejzeeyxgsw.supabase.co, eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4aHBubWR2c3hlanplZXl4Z3N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDIyNTUsImV4cCI6MjA3MjExODI1NX0.kKySqSzyEnxwkHRKT6PdUlE2_UjEjWZhTDyVO-m7O70;);
